name: talesofmajeyal
version: '1.5.8'
summary: A free, open source roguelike RPG
description: |
  Tales of Maj’Eyal is a free, open source roguelike RPG, featuring tactical turn-based combat and advanced character building.  Play as one of many unique races and classes in the lore-filled world of Eyal, exploring random dungeons, facing challenging battles, and developing characters with your own tailored mix of abilities and powers.  With a modern graphical and customisable interface, intuitive mouse control, streamlined mechanics and deep, challenging combat, Tales of Maj’Eyal offers engaging roguelike gameplay for the 21st century.

grade: stable
confinement: strict

apps:
  talesofmajeyal:
    command: desktop-launch $SNAP/launch.sh
    plugs: [ unity7, joystick, pulseaudio, opengl, network ]

parts:
  launcher:
    plugin: dump
    source: scripts
  tengine:
    source: https://te4.org/do-download/tome-1.5.8/t-engine4-linux64-1.5.8.tar.bz2
    after: [ desktop-glib-only ]
    plugin: make
    artifacts:
      - .
    make-parameters: [ config=release ]
    build-packages:
      - premake4
      - sed
      - make
      - gcc
      - libsdl2-dev
      - libsdl2-image-dev
      - libsdl2-ttf-dev
      - libopenal-dev
      - libogg-dev
      - libpng12-dev
      - libvorbis-dev
      - libglu1-mesa-dev
      - libfreetype6-dev
      - xorg-dev
      - libasound2-dev
      - libaudiofile-dev
      - libpulse-dev
    stage-packages:
      - libsdl2-2.0-0
      - libsdl2-image-2.0-0
      - libsdl2-ttf-2.0-0
    prepare: |
      sed -i "s|opt/SDL-2.0|usr|" premake4.lua
      premake4 gmake
