name: talesofmajeyal
version: '1.7.0'
summary: A free, open source roguelike RPG
description: |
  Tales of Maj’Eyal is a free, open source roguelike RPG, featuring tactical turn-based combat and advanced character building.  Play as one of many unique races and classes in the lore-filled world of Eyal, exploring random dungeons, facing challenging battles, and developing characters with your own tailored mix of abilities and powers.  With a modern graphical and customisable interface, intuitive mouse control, streamlined mechanics and deep, challenging combat, Tales of Maj’Eyal offers engaging roguelike gameplay for the 21st century.

base: core18
grade: stable
confinement: strict

apps:
  talesofmajeyal:
    command: launch.sh
    plugs: [ unity7, joystick, pulseaudio, opengl, network ]
    extensions: [gnome-3-28]

parts:
  launcher:
    plugin: dump
    source: scripts

  tengine:
    source: https://te4.org/dl/t-engine/t-engine4-src-1.7.0.tar.bz2
    plugin: make
    artifacts:
      - .
    make-parameters: [ config=release ]
    build-packages:
      - premake4
      - sed
      - make
      - gcc
      - libsdl2-dev
      - libsdl2-image-dev
      - libsdl2-ttf-dev
      - libopenal-dev
      - libogg-dev
      - libpng-dev
      - libvorbis-dev
      - libglu1-mesa-dev
      - libfreetype6-dev
      - xorg-dev
      - libasound2-dev
      - libaudiofile-dev
      - libpulse-dev
    stage-packages:
      - libsdl2-2.0-0
      - libsdl2-image-2.0-0
      - libsdl2-ttf-2.0-0
      - libopenal1
      - libmad0
      - libogg0
      - libvorbis0a
      - libpng16-16
      - libgl1-mesa-glx
      - libglu1-mesa
      - libvorbisfile3
    override-build: |
      sed -i "s|opt/SDL-2.0|usr|" premake4.lua
      premake4 gmake
      snapcraftctl build

  cleanup:
    after: [launcher, tengine]
    plugin: nil
    build-snaps:
      - core18
      - gtk-common-themes
      - gnome-3-28-1804
    override-prime: |
      set -eux
      for snap in "core18" "gtk-common-themes" "gnome-3-28-1804"; do
        cd "/snap/$snap/current" && find . -type f,l -exec rm -r "$SNAPCRAFT_PRIME/{}" \;
      done

